site_name: goalgos
site_url: https://jeyabalajis.github.io/goalgos/
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
theme:
  name: material
nav:
  - Home: index.md
  - 'Graph':
    - 'Tree':      
      - 'Maximum sum possible in a tree': 'graph/max-sum-possible-tree.md'
      - 'Same Tree': 'graph/same-tree.md'
  - 'String':
    - 'Word Break':
      - 'Break Sentence by Sub String': 'string/break-sentence-by-substr.md'
  - 'Optimization':
    - 'Scheduling':
      - 'Schedule Courses': 'optimization/schedule-courses.md'
    - 'Network':
      - 'Cheapest flights within k stops': 'optimization/cheapest-flights-within-k-stops.md'
